"""update Vendor field

Revision ID: 972d5cd703c4
Revises: eef235e9892f
Create Date: 2024-10-08 21:47:55.373386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972d5cd703c4'
down_revision = 'eef235e9892f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vendor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('google_id')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
