"""add the is_verified field into Customer model

Revision ID: e8e40ae45628
Revises: c22edc628bd3
Create Date: 2024-09-19 15:41:09.034197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e40ae45628'
down_revision = 'c22edc628bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
